### ISSUE TITLE
js代码片段无法运行，预览无反应，控制台无报错

### ISSUE THREAD

**Issue by mjt233** [philipxiaoxi/webmaker-frontend#20]
以下代码无法通过webmaker执行和输出结果
```js
const s1 = 'ab', s2 = 'eidbaooo'
const n = s1.length, m = s2.length
if (n > m) {
  return false
}
const cnt1 = new Array(26).fill(0)
const cnt2 = new Array(26).fill(0)
for (let i = 0; i < n; ++i) {
  ++cnt1[s1[i].charCodeAt() - 'a'.charCodeAt()]
  ++cnt2[s2[i].charCodeAt() - 'a'.charCodeAt()]
}
console.log(cnt1, cnt2)
```

注释以下代码后正常：
```js
if (n > m) {
  return false
}
```

**Comment by philipxiaoxi** [comment]
您好，在一个顺序执行的js代码块中(<script></script>)，您不能使用`return`语句。
请使用函数包裹，方可使用`return`语句。
![image](https://user-images.githubusercontent.com/52746230/175764389-54f7393d-44d1-4766-b251-65dce046e72e.png)

根据js规范，具体原因有以下：

1. return语句只能出现在函数体内，出现在代码中的其他任何地方都会造成语法错误！
2. 在未被函数包裹的if语句中，内部是不能使用return作为结束的（貌似是新标准），但可以使用break来[中断]

您可以查找更多有关资料。最后感谢您的反馈。

**Comment by mjt233** [comment]
可以考虑采用eval或new Function的形式去调用代码来解决这个问题么

**Comment by philipxiaoxi** [comment]
您是否有这个需求呢？

**Comment by philipxiaoxi** [comment]
` 考虑采用eval或new Function的形式` 该形式是可以的。 系统也可以为您的代码包装一层函数，从而避免这个问题，后期会进行调研讨论，预计第三版迭代新增到个人中心配置当中，届时您可以开启该选项。
